### ISSUE TITLE
Unclear firewall guidelines

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#107]
Page: [Whitelist Ports and IP Addresses](https://docs.netapp.com/us-en/kubernetes-service/whitelist-ports-and-ip-addresses.html)

"If you decide to restrict access to your cluster, you will need to whitelist the following ports and IP addresses"

Where? Firewall, mNode, vCenter (I hope not), all of the above? Outgoing or incoming?

**Comment by ebarcott** [comment]
Any of the above. We occasionally have customers who want to set up their own firewall rules with their own systems, and want to know which IP addresses to whitelist. We also occasionally see NetApp employees behind a firewall who need to know what IP addresses to whitelist so that they can access from work. The language in this article is left deliberately vague to cover all the potential reasons why someone would want the IP address info, without providing any guidance as to how or why to set that up, which is beyond the scope of NKS support docs.
